// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var $postMedia, $postMediaImg, img, postMediaImgAspectRatio, resizeBg, theWindow;
    $('header h1 a').on('click', function(event) {
      event.preventDefault();
      return $('header').toggleClass('active');
    });
    $(window).on('scroll', function() {
      return $('header').removeClass('active');
    });
    if ($("body").hasClass("fullImage")) {
      theWindow = $(window);
      $postMedia = $(".postMedia");
      $postMediaImg = $(".postMedia img");
      postMediaImgAspectRatio = 1;
      img = $postMediaImg[0];
      $("<img/>").attr("src", $(img).attr("src")).load(function() {
        var pic_real_height, pic_real_width;
        pic_real_width = this.width;
        pic_real_height = this.height;
        return postMediaImgAspectRatio = pic_real_width / pic_real_height;
      });
      resizeBg = function() {
        if ((theWindow.width() / theWindow.height()) < postMediaImgAspectRatio * 0.9) {
          $postMedia.css("height", "auto");
          return console.log("we're good");
        } else {
          console.log("what up");
          return $postMedia.css("height", theWindow.height() * 0.9);
        }
      };
      return theWindow.resize(resizeBg).trigger("resize");
    }
  });

}).call(this);
