#!/bin/bash

if [[ -z "$@" ]]; then
  java -server -Xmx512m -XX:MaxPermSize=200m -jar deploy/jars/weirdcanada-distro.jar -Drun.mode=production
else
  java -server -Xmx512m -XX:MaxPermSize=200m -jar deploy/jars/weirdcanada-distro.jar "$@"
fi
