#!/bin/bash

if [[ -z "$@" ]]; then
  java -server -Xmx800m -XX:MaxPermSize=200m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -Drun.mode=production -jar deploy/jars/weirdcanada-distro.jar
else
  java -server -Xmx512m -XX:MaxPermSize=200m -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -jar deploy/jars/weirdcanada-distro.jar "$@"
fi
