#!/bin/bash

# get current directory of script
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source "$DIR"/bash_variables

for file in "$@"
do
	if [ ${file#*.} = "mp3" ]
	then
		MP3_FILE="$file"
		WAV_FILE=${MP3_FILE%.*}".wav"
		OGG_FILE=${MP3_FILE%.*}".ogg"

		echo ">> ... converting $MP3_FILE to wav"

		mpg123 -w $WAV_FILE $MP3_FILE

		echo ">> ... converting $WAV_FILE to ogg"

		oggenc $WAV_FILE
		
		echo ">> ... uploading $MP3_FILE"

    s3cmd put --acl-public --guess-mime-type $MP3_FILE "s3://wc-tracks/$MP3_FILE"

		echo ">> ... uploading $OGG_FILE"

    s3cmd put --acl-public --guess-mime-type $OGG_FILE "s3://wc-tracks/$OGG_FILE"

		echo "
<audio controls=\"controls\" class=\"audioTrack\" preload=\"none\">
	<source src=\"https://s3.amazonaws.com/wc-tracks/$OGG_FILE\" type='audio/ogg; codecs=\"vorbis\"' />
	<source src=\"https://s3.amazonaws.com/wc-tracks/$MP3_FILE\" type='audio/mpeg; codecs=\"mp3\"' />
</audio>
<p class=\"audioTrack\"><a href=\"https://s3.amazonaws.com/wc-tracks/$MP3_FILE\" target=\"_blank\">TRACKNAME</a></p>
"

		rm $WAV_FILE
    rm $OGG_FILE
	fi
done

exit
